name: AWS EKS Node Group
on:
  push:
    paths:
      - 'aws/eks-node-group/**'
jobs:
  terraform:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./aws/eks-node-group/example
          args: validate
