name: AWS Network
on:
  push:
    paths:
      - 'aws/network/**'
jobs:
  terraform:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./aws/network/example
          args: validate
