name: AWS Certificate
on:
  push:
    paths:
      - 'aws/certificate/**'
jobs:
  terraform:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./aws/certificate/example
          args: validate
