name: AWS Tests
on:
  push:
    paths:
      - 'aws/**'
      - 'test/aws/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Lint
        uses: gardenbed/actions/go-lint@main
        with:
          path: ./test/aws
