name: Google Tests
on:
  push:
    paths:
      - 'google/**'
      - 'test/google/**'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Lint
        uses: gardenbed/actions/go-lint@main
        with:
          path: ./test/google
