name: Google Labels
on:
  push:
    paths:
      - 'google/labels/**'
jobs:
  terraform:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: gardenbed/actions/terraform@main
        with:
          path: ./google/labels/example
          args: validate
